from __future__ import annotations

import argparse

from timetable.constants import CliAction, CliArgument
from timetable.services.database_service import DatabaseService


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Create an empty SQLite timetable database."
    )
    parser.add_argument(
        CliArgument.DATABASE.value,
        help="Database name or path. Missing .sqlite3 suffix is added automatically.",
    )
    parser.add_argument(
        CliArgument.DROP_EXISTING.value,
        action=CliAction.STORE_TRUE.value,
        help="Drop existing tables before creating the schema.",
    )
    parser.add_argument(
        CliArgument.ECHO_SQL.value,
        action=CliAction.STORE_TRUE.value,
        help="Print SQL generated by SQLAlchemy.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    database = DatabaseService(args.database, echo=args.echo_sql)
    database.create_schema(drop_existing=args.drop_existing)
    print(f"Database schema created: {database.database_path}")


if __name__ == "__main__":
    main()
