from __future__ import annotations

import argparse
from pathlib import Path

from timetable.services.database_service import DatabaseService
from timetable.services.gtfs_loader import GtfsLoader


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Load GTFS ZIP data into the timetable database."
    )
    parser.add_argument("gtfs_zip", type=Path, help="Path to a GTFS ZIP package.")
    parser.add_argument(
        "database",
        help="Database name or path. Missing .sqlite3 suffix is added automatically.",
    )
    parser.add_argument(
        "--batch-size",
        type=int,
        default=5000,
        help="Number of rows inserted in one batch.",
    )
    parser.add_argument(
        "--replace",
        action="store_true",
        help="Remove existing timetable rows before importing the ZIP package.",
    )
    parser.add_argument(
        "--echo-sql",
        action="store_true",
        help="Print SQL generated by SQLAlchemy.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    database = DatabaseService(args.database, echo=args.echo_sql)
    database.create_schema()

    with database.session() as session:
        loader = GtfsLoader(session=session, batch_size=args.batch_size)
        summary = loader.load_zip(args.gtfs_zip, replace_existing=args.replace)

    print("Import completed:")
    for line in summary.as_lines():
        print(f"  {line}")


if __name__ == "__main__":
    main()
